[project]
# Support Python 3.11+.
requires-python = ">=3.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

# Add more settings from tools that add support for `pyproject.toml`
# https://github.com/carlosperate/awesome-pyproject

[tool.poetry]
name = "semfealumni"
version = "2024.2.3"
description = ""
license = ""
authors = []

[tool.poetry.dependencies]
python = "^3.11"
mkdocs = "^1.5"
mkdocs-material = { version = "^9.5", extras = ["imaging"] }
mkdocs-gen-files = "^0.5"
mkdocs-literate-nav = "^0.6"
mkdocs-section-index = "^0.3"
pymdown-extensions = "^10.7"
mkdocs-pdf = "^0.1"
mkdocs-rss-plugin = "^1.12"
